### ISSUE TITLE
Not searching local PDF files? + others

### ISSUE THREAD

**Issue by laz91AU** [lunu-bounir/search-all-tabs#2]
Not sure if these are bugs or not but:

- Even after allowing access to urls in the chrome extension manager, it doesn't seem to search local pdf files that i open in chrome

- when i open the popout box to search it sometimes dumps the text from my clipboard after a 1 second delay

- would there be any way to get the addon to preserve my last search if after the popup is closed and reopened? Sometimes i think i've found the tab I want but then realise it's not so have to re-run the same search

**Comment by lunu-bounir** [comment]
> Even after allowing access

Unfortunately, in-tab PDF files that are opened either by Chrome or another extension is considered as local extension page and due to privacy concerns, these pages are not indexable. Only the original extension can access to its local pages. As of the next release, the number of tabs that are being ignored will be displayed in the popup.

> when i open the popout box to search it sometimes dumps the text from my clipboard

It is not your clipboard content, but the selected text in the document.

> would there be any way to get the addon to preserve my last search

Thanks for the feature suggestion. We will have two new modes on the next release;
![Screen Shot 2019-10-05 at 11 24 01 AM](https://user-images.githubusercontent.com/40388903/66253601-a7374180-e75a-11e9-9177-d0fea19102c6.png)
